name: datetime_picker_field_platform_example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  datetime_picker_field_platform:
    path: ../
  
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true