name: datetime_picker_field_platform
description: A TextFormField widget that allows people to choose the time or date following Material and Cupertino design.
version: 0.0.1
homepage: https://github.com/JherysVargas/datetime_picker_field_platform

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  jiffy: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
